### ISSUE TITLE
Feature Request: Be able to fetch data from restricted sheet

### ISSUE THREAD

**Issue by HuyAms** [gglukmann/use-google-sheets#23]
Hi,

Now, we can only fetch data from a sheet that has the permission "Anyone with this link can view". Is it possible that we can also read the data from a restricted sheet (only shared with some specific emails)?

**Comment by gglukmann** [comment]
Hi, to see data from restricted sheet, you'll need to do it from backend or every user should log in etc. This library is client side only.
